### ISSUE TITLE
raco test hello-world-test.rkt not working.

### ISSUE THREAD

**Issue by bnsv** [exercism/racket#153]
Hello,
I trying to run ``$ raco test hello-world-test.rkt
`` from ~/exercism/racket/hello-world but got
```
provide: provided identifier is not defined or required
  at: hello
  in: (#%provide (expand (provide-trampoline hello)))
  location...:
   hello-world.rkt:3:9
```
I am using Racket v7.7. I never touch the original rkt code and the test.ekt-code provided from `` exercism download --exercise=hello-world --track=racket
`` before, except only running above ``raco test`` command. 

Is it a bug?
